export const subscriptionPlans = [
  {
    id: 'free',
    name: 'FREE',
    price: '₹0',
    billingPeriod: 'forever',
    duration: 'Forever',
    description: 'For solo founders and early experiments.',
    features: ['1 Project', '5 Members', '100 Issues'],
    highlight: false,
    accent: 'slate',
  },
  {
    id: 'starter',
    name: 'STARTER',
    price: '₹399',
    billingPeriod: '/month',
    duration: '30 days',
    description: 'For growing product teams that need momentum.',
    features: ['5 Projects', '25 Members', 'Unlimited Issues'],
    highlight: true,
    accent: 'indigo',
  },
  {
    id: 'business',
    name: 'BUSINESS',
    price: '₹999',
    billingPeriod: '/month',
    duration: '30 days',
    description: 'For scaling organizations with broader coordination.',
    features: ['15 Projects', '100 Members', 'Unlimited Issues'],
    highlight: false,
    accent: 'violet',
  },
  {
    id: 'enterprise',
    name: 'ENTERPRISE',
    price: 'Contact Sales',
    billingPeriod: '',
    duration: 'Custom',
    description: 'For large organizations with bespoke needs.',
    features: ['Unlimited', 'Unlimited', 'Unlimited'],
    highlight: false,
    accent: 'sky',
  },
];
